apiVersion: v1
kind: Template
metadata:
  name: '${APP_NAME}'
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: '${APP_NAME}'
      namespace: ${NAMESPACE}
      labels:
        app: '${APP_NAME}'
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
      replicas: 1
      revisionHistoryLimit: 5
      test: false
      selector:
        app: '${APP_NAME}'
        deploymentconfig: '${APP_NAME}'
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: '${APP_NAME}'
            deploymentconfig: '${APP_NAME}'
        spec:
          containers:
            - resources:
                limits:
                  cpu: '1'
                  memory: 2Gi
                requests:
                  cpu: 50m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              name: '${APP_NAME}'
              ports:
                - containerPort: 6001
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              image: '${REGISTRY_URL}'
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
parameters:
  - name: REGISTRY_URL
    displayName: OpenShift Container Registry
    description: URL of the container in Registry (baseUrl/container-name:version)
    required: true
  - name: APP_NAME
    displayName: Application Name
    description: Unique application name
    required: true
  - name: NAMESPACE
    displayName: Service Name
    description: Unique service name
    required: true